# Pipeline for Test tools

pool: 
  name: Rabo-Linux-Production

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14'
  displayName: 'Install Node.js'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'xat.zos.rabobank.nl ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNt64+SlD9DCxrjviIN3qYOEj+mn3h0H2CPPW2KATua2HFYJ3NGrIM9a5j3ie7WjtLKQObMIwxEOeTrNasPJTkE='
    sshPublicKey: '$(xat-gis-testtools-test)' 
    sshKeySecureFile: 'xat-gis-testtools-test' 
  displayName: Install xat SSH Key

- task: DownloadSecureFile@1
  name: zosmfCertificate
  displayName: 'Download certificate for zosmf'
  inputs:
    secureFile: 'clientcert-xat.crt' 

- task: DownloadSecureFile@1
  name: zosmfCertificateKey
  displayName: 'Download certificate key for zosmf'
  inputs:
    secureFile: 'clientcert-xat.privkey'

- task: DownloadSecureFile@1
  name: xatsshKey
  displayName: 'Download key for ssh'
  inputs:
    secureFile: 'niek_xat_id_rsa'

- bash: echo $(Build.SourceBranch)
- bash: ls ./src
- bash: ls $(zosmfCertificate.secureFilePath); ls $(xatsshKey.secureFilePath)
- bash: cat buildpackage.xml

- script: |
    npm install -g @zowe/cli@zowe-v2-lts
    zowe --version
    mv ./src/imperative.json ~/.zowe/settings
    zowe profiles create zosmf-profile xat-dev-zosmf --host zoswfx1-xat.zos.rabobank.nl --port 443 --cert-file $(zosmfCertificate.secureFilePath) --cert-key-file $(zosmfCertificateKey.secureFilePath) --reject-unauthorized false
    zowe profiles create ssh-profile xat-dev-ssh --host zoswfx1-xat.zos.rabobank.nl --port 22 --pk $(xatsshKey.secureFilePath) --user GREEFDN
  displayName: 'Prepare Zowe CLI'

# Ant
# Build with Apache Ant
- task: Ant@1
  inputs:
    buildFile: "buildpackage.xml" 

- script: |
    zowe zos-ssh issue command "mkdir -p /u/greefdn/gis-testtools/dev"
    zowe files ul dtu "./src" "/u/greefdn/gis-testtools/dev" -b -r
    zowe files ul dtu "dist" "/u/greefdn/gis-testtools/dev" -b -r
    zowe zos-ssh issue command "cd /u/greefdn/gis-testtools/dev; echo | ls -al"
    zowe zos-ssh issue command "chmod 755 /u/greefdn/gis-testtools/dev/*; ls -al /u/greefdn/gis-testtools/dev"
  displayName: 'Deploying testtools to XAT development'

- script: |
    zowe zos-ssh issue command "/u/greefdn/gis-testtools/dev/testmqjava.sh"
    zowe zos-ssh issue command "python3 /u/greefdn/gis-testtools/dev/testmq.py /u/greefdn/pythonprograms/dwc-client-ssl-xat.crt /u/greefdn/pythonprograms/dwc-client-ssl-xat.privkey"
  displayName: 'Testing testtools to XAT development'  
